

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Unit Tests

on:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '12.x'
      - uses: actions/cache@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.1'
      - run: flutter pub get
      - run: flutter test
      #- run: flutter build apk
      #- run: flutter build appbundle   
